function ensureRecoveryItems(){let b=item('bottle');if(b&&!b.consume)b.consume={type:'drink',amount:3,uses:3,maxUses:3,emptyWeight:.2,unitWeight:.3};let br=item('bread');if(br&&!br.consume)br.consume={type:'food',amount:3,remove:true};if(b?.consume?.type==='drink'){if(b.consume.uses==null)b.consume.uses=b.consume.maxUses??3;if(b.consume.maxUses==null)b.consume.maxUses=3;if(b.consume.emptyWeight==null)b.consume.emptyWeight=.2;if(b.consume.unitWeight==null)b.consume.unitWeight=.3;b.weight=b.consume.emptyWeight+b.consume.unitWeight*b.consume.uses;if(b.consume.uses<=0)b.name='空の水筒'}}
function humanItem(it){let p=it?.parent,seen=new Set();while(p){if(p==='main'||p==='loose')return true;if(p==='pet')return false;if(!p.startsWith('container:'))return false;let id=p.slice(10);if(seen.has(id))return false;seen.add(id);p=item(id)?.parent}return false}
function recoveryItems(){ensureRecoveryItems();return state.items.filter(it=>humanItem(it)&&it.consume&&(it.consume.type==='food'||(it.consume.type==='drink'&&(it.consume.uses??0)>0)))}
function recoverHealth(amount){let max=state.maxHealth??10,old=state.health??max;state.health=Math.min(max,old+amount);return state.health-old}
function useRecoveryItem(id){let it=item(id);if(!it||!humanItem(it)||!it.consume)return;let max=state.maxHealth??10;if((state.health??max)>=max)return toast('体力は満タンです');let c=it.consume,name=it.name,gain=recoverHealth(c.amount||3);if(c.type==='food'){if(c.remove)state.items=state.items.filter(x=>x.id!==id);toast(name+'を食べて体力 +'+gain)}else if(c.type==='drink'){c.uses=Math.max(0,(c.uses??0)-1);it.weight=(c.emptyWeight??.2)+(c.unitWeight??.3)*c.uses;if(c.uses<=0)it.name='空の水筒';toast('水を飲んで体力 +'+gain)}markDirty();render();renderHealthMenu()}
function sleepRecovery(){let max=state.maxHealth??10;if((state.health??max)>=max)return toast('体力は満タンです');let gain=recoverHealth(5);markDirty();render();renderHealthMenu();toast('眠って体力 +'+gain)}
function renderHealthMenu(){let max=state.maxHealth??10,cur=state.health??max,full=cur>=max,items=recoveryItems();$('healthMeta').textContent='体力 '+cur+' / '+max+(full?' ・ 満タン':'');let a=$('healthActions');a.innerHTML='';for(let it of items){let c=it.consume,b=document.createElement('button');let verb=c.type==='food'?'食べる':'飲む',detail=c.type==='drink'?' ・ 残り '+(c.uses??0)+' / '+(c.maxUses??c.uses??0):'';b.textContent=it.icon+' '+it.name+'を'+verb+'　体力 +'+(c.amount||3)+detail;b.disabled=full;b.onclick=()=>useRecoveryItem(it.id);a.appendChild(b)}if(!items.length){let n=document.createElement('div');n.className='note';n.textContent='食べ物や飲み物は所持していません。';a.appendChild(n)}let sleep=document.createElement('button');sleep.textContent='眠る　体力 +5';sleep.disabled=full;sleep.onclick=sleepRecovery;a.appendChild(sleep)}
function openHealth(){if(!activeId)return toast('先にセーブデータを作ってください');renderHealthMenu();$('healthLayer').classList.add('open')}
function closeHealth(){$('healthLayer').classList.remove('open')}
$('healthStat').addEventListener('click',openHealth);$('closeHealth').addEventListener('click',closeHealth);$('healthLayer').addEventListener('click',e=>{if(e.target===$('healthLayer'))closeHealth()});
