function total(it,seen=new Set()){if(!it||seen.has(it.id))return 0;seen.add(it.id);return it.weight+kids(it.id).reduce((a,x)=>a+total(x,seen),0)}
function topWeight(p){return state.items.filter(x=>x.parent===p).reduce((a,x)=>a+total(x),0)}function insideWeight(id){return kids(id).reduce((a,x)=>a+total(x),0)}
function spec(id){if(id==='main')return{cols:8,rows:6};if(id==='pet')return{cols:6,rows:4};return item(id)?.inner||null}function parentFor(id){return id==='main'||id==='pet'?id:'container:'+id}function inGrid(id,exclude){return state.items.filter(x=>x.parent===parentFor(id)&&x.id!==exclude)}
function parentContainer(it){return it.parent?.startsWith('container:')?it.parent.slice(10):null}function cycle(itemId,target){let c=target,seen=new Set();while(c&&!seen.has(c)){if(c===itemId)return true;seen.add(c);c=parentContainer(item(c)||{})}return false}
function fits(it,g,x,y){let s=spec(g);if(!s||x<0||y<0||x+it.w>s.cols||y+it.h>s.rows)return false;return !inGrid(g,it.id).some(o=>x<o.x+o.w&&x+it.w>o.x&&y<o.y+o.h&&y+it.h>o.y)}
function weightError(){if(topWeight('main')>state.humanMax+.001)return'人が持てる重量を超えます';if(topWeight('pet')>state.petMax+.001)return'ペットが持てる重量を超えます';for(let c of state.items.filter(x=>x.inner))if(insideWeight(c.id)>c.inner.maxWeight+.001)return c.name+'の中身が重すぎます';return null}
function move(id,g,x,y){let it=item(id);if(!it)return;if(g!=='main'&&g!=='pet'&&cycle(id,g))return toast('収納を自分自身の中には入れられません');if(!fits(it,g,x,y))return toast('そこには入りません');let old={parent:it.parent,x:it.x,y:it.y};it.parent=parentFor(g);it.x=x;it.y=y;let er=weightError();if(er){Object.assign(it,old);return toast(er)}markDirty();render()}
function toLoose(id){let it=item(id);it.parent='loose';delete it.x;delete it.y;markDirty();render()}function cell(){return parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--cell'))||36}
function sizeGrid(el,id){let s=spec(id),c=cell();el.style.width=s.cols*c+'px';el.style.height=s.rows*c+'px'}
function card(it,gridMode){let e=document.createElement('div'),c=cell();e.className='item '+(gridMode?'grid-item':'loose-item')+' '+it.kind+(it.inner?' storage':'');e.dataset.item=it.id;e.style.width=it.w*c-4+'px';e.style.height=it.h*c-4+'px';if(gridMode){e.style.left=it.x*c+'px';e.style.top=it.y*c+'px'}e.innerHTML='<span><span class="icon">'+it.icon+'</span>'+it.name+'</span><span class="kg">'+total(it).toFixed(1)+'kg</span>';e.addEventListener('pointerdown',down);return e}
function renderGrid(el,id){sizeGrid(el,id);el.innerHTML='';inGrid(id).forEach(x=>el.appendChild(card(x,true)))}function renderLoose(){let l=$('looseList');l.innerHTML='';state.items.filter(x=>x.parent==='loose').forEach(x=>l.appendChild(card(x,false)))}
function render(){ensureConsumables();let h=topWeight('main'),p=topWeight('pet');$('indexWeight').textContent=h.toFixed(1);$('mainWeight').textContent=h.toFixed(1);$('petWeight').textContent=p.toFixed(1);$('charIndexName').textContent=state.characterName||'旅人';$('headerChar').textContent=activeId?(state.characterName||'旅人'):'セーブ未選択';$('dayValue').textContent=state.day??1;$('locationValue').textContent=state.location||'街道沿い';$('healthValue').textContent=(state.health??10)+' / '+(state.maxHealth??10);$('hungerValue').textContent=(state.hunger??2)+' / '+(state.maxHunger??10);$('thirstValue').textContent=(state.thirst??2)+' / '+(state.maxThirst??10);$('moneyValue').textContent='¥'+(state.money??380);renderLoose();renderGrid($('mainGrid'),'main');renderGrid($('petGrid'),'pet');if(openId)renderStorage(openId);updateSaveState()}
function renderStorage(id){let c=item(id);if(!c?.inner)return closeStorage();openId=id;$('storageTitle').textContent=c.name;$('storageMeta').textContent='中身 '+insideWeight(id).toFixed(1)+' / '+c.inner.maxWeight.toFixed(1)+' kg ・ '+c.inner.cols+' × '+c.inner.rows+' マス';$('storageGrid').dataset.grid=id;renderGrid($('storageGrid'),id)}function openStorage(id){openId=id;$('storageLayer').classList.add('open');renderStorage(id)}function closeStorage(){openId=null;$('storageLayer').classList.remove('open')}
function info(it){let c=it.consume,action='';if(c?.type==='food')action='<br><button class="consume-action" onclick="window.consumeDrifterItem(\''+it.id+'\')">食べる</button>';if(c?.type==='drink'){let left=c.uses??0;action='<br><span class="chip">残り '+left+' / '+(c.maxUses??left)+'</span><br><button class="consume-action" '+(left<=0?'disabled':'')+' onclick="window.consumeDrifterItem(\''+it.id+'\')">'+(left<=0?'空です':'飲む')+'</button>'}$('info').innerHTML='<strong>'+it.icon+' '+it.name+'</strong><br><span class="chip">大きさ '+it.w+'×'+it.h+'</span><span class="chip">本体 '+it.weight.toFixed(1)+'kg</span>'+(it.inner?'<span class="chip">収納 '+it.inner.cols+'×'+it.inner.rows+'</span><span class="chip">中身上限 '+it.inner.maxWeight.toFixed(1)+'kg</span>':'')+action}
function down(e){if(!activeId)return toast('先にセーブデータを作ってください');if(e.button!==undefined&&e.button!==0)return;let src=e.currentTarget;drag={id:src.dataset.item,src,startX:e.clientX,startY:e.clientY,pid:e.pointerId,moved:false,ghost:null};src.setPointerCapture?.(e.pointerId);window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',up,{once:true});window.addEventListener('pointercancel',up,{once:true})}
function dragMove(e){if(!drag||e.pointerId!==drag.pid)return;let d=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY);if(!drag.moved&&d>7){drag.moved=true;drag.src.classList.add('src');drag.ghost=drag.src.cloneNode(true);drag.ghost.classList.remove('grid-item','loose-item','src');drag.ghost.classList.add('ghost');drag.ghost.style.left='';drag.ghost.style.top='';document.body.appendChild(drag.ghost)}if(drag.moved){e.preventDefault();drag.ghost.style.left=e.clientX+'px';drag.ghost.style.top=e.clientY+'px';mark(e.clientX,e.clientY)}}
function under(x,y){if(drag?.ghost)drag.ghost.style.display='none';let u=document.elementFromPoint(x,y);if(drag?.ghost)drag.ghost.style.display='';return u}
function gridNear(x,y,pad=22){let best=null,bestD=Infinity;document.querySelectorAll('.grid').forEach(g=>{let r=g.getBoundingClientRect();if(x<r.left-pad||x>r.right+pad||y<r.top-pad||y>r.bottom+pad)return;let dx=x<r.left?r.left-x:x>r.right?x-r.right:0,dy=y<r.top?r.top-y:y>r.bottom?y-r.bottom:0,d=dx*dx+dy*dy;if(d<bestD){bestD=d;best=g}});return best}
function mark(x,y){document.querySelectorAll('.grid.over,.loose.over').forEach(x=>x.classList.remove('over'));let direct=under(x,y)?.closest('.grid,.loose');(direct||gridNear(x,y))?.classList.add('over')}
function bestDrop(g,it,px,py){let id=g.dataset.grid,s=spec(id);if(!id||!s)return null;let c=cell(),r=g.getBoundingClientRect(),maxX=s.cols-it.w,maxY=s.rows-it.h;if(maxX<0||maxY<0)return null;let x=Math.round((px-r.left-2-it.w*c/2)/c),y=Math.round((py-r.top-2-it.h*c/2)/c);x=Math.max(0,Math.min(maxX,x));y=Math.max(0,Math.min(maxY,y));if(fits(it,id,x,y))return{x,y};let candidates=[];for(let yy=Math.max(0,y-1);yy<=Math.min(maxY,y+1);yy++)for(let xx=Math.max(0,x-1);xx<=Math.min(maxX,x+1);xx++)if(fits(it,id,xx,yy)){let cx=r.left+2+(xx+it.w/2)*c,cy=r.top+2+(yy+it.h/2)*c;candidates.push({x:xx,y:yy,d:(cx-px)**2+(cy-py)**2})}candidates.sort((a,b)=>a.d-b.d);return candidates[0]||null}
function up(e){if(!drag)return;window.removeEventListener('pointermove',dragMove);document.querySelectorAll('.grid.over,.loose.over').forEach(x=>x.classList.remove('over'));let d=drag;drag=null;d.src.classList.remove('src');d.ghost?.remove();let it=item(d.id);if(!d.moved){it.inner?openStorage(it.id):info(it);return}let els=document.querySelectorAll('[data-item="'+it.id+'"]');els.forEach(x=>x.style.pointerEvents='none');let u=document.elementFromPoint(e.clientX,e.clientY);els.forEach(x=>x.style.pointerEvents='');if(u?.closest('#loose'))return toLoose(it.id);let g=u?.closest('.grid')||gridNear(e.clientX,e.clientY);if(!g)return toast('移動をキャンセルしました');let pos=bestDrop(g,it,e.clientX,e.clientY);if(!pos)return toast('そこには入りません');move(it.id,g.dataset.grid,pos.x,pos.y)}
