const GH_OWNER='namiyukuta-cmd',GH_REPO='WorthlessDrifter-rpg',SAVE_BRANCH='main',SAVE_DIR='saves/characters',TOKEN_KEY='drifter-github-token-local';
function uid(){return'D'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function apiUrl(path){return'https://api.github.com/repos/'+GH_OWNER+'/'+GH_REPO+'/'+path}
function ghHeaders(){let h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(githubToken)h.Authorization='Bearer '+githubToken;return h}
async function ghJson(url,options={}){let res;try{res=await fetch(url,{cache:'no-store',...options,headers:{...ghHeaders(),...(options.headers||{})}})}catch(e){let err=new Error('ブラウザからGitHub APIへ接続できませんでした');err.cause=e;throw err}let data=null;try{data=await res.json()}catch(e){}if(!res.ok){let msg=data?.message||('GitHub HTTP '+res.status);let err=new Error(msg);err.status=res.status;throw err}return data}
function toBase64(text){let b=new TextEncoder().encode(text),s='';for(let x of b)s+=String.fromCharCode(x);return btoa(s)}
function fromBase64(text){let s=atob(String(text||'').replace(/\n/g,'')),b=new Uint8Array(s.length);for(let i=0;i<s.length;i++)b[i]=s.charCodeAt(i);return new TextDecoder().decode(b)}
function requireToken(){if(githubToken)return true;openSave(false);$('tokenInput').focus();toast('GitHub接続が必要です');return false}
function friendlyError(e){let msg=e?.message||'GitHub通信に失敗しました';if(e?.status===401)return'401：トークンがGitHubに認証されませんでした（'+msg+'）';if(e?.status===403)return'403：GitHubへの書き込みが拒否されました（'+msg+'）';if(e?.status===404)return'404：保存先または対象リポジトリが見つかりません（'+msg+'）';if(e?.status)return e.status+'：'+msg;return msg}
function markDirty(){if(!activeId)return;dirty=true;updateSaveState()}
function updateSaveState(){let e=$('saveState');if(!activeId){e.textContent='—';e.classList.remove('dirty');$('headerChar').textContent='セーブ未選択';return}e.textContent=dirty?'未保存':'GitHub保存済';e.classList.toggle('dirty',dirty);$('headerChar').textContent=state.characterName}
function updateGitHubStatus(msg,bad=false){let e=$('githubStatus');if(msg){e.textContent=msg;e.classList.toggle('bad',bad);e.classList.toggle('ok',!bad);return}if(githubToken){e.textContent='接続情報を登録済み（SAVE時にGitHub書き込みを確認します）';e.classList.add('ok');e.classList.remove('bad')}else{e.textContent='未接続（GitHubのセーブ一覧は読み込めます）';e.classList.remove('ok','bad')}}
function connectGitHub(){let token=$('tokenInput').value.trim();if(!token)return toast('トークンを入力してください');githubToken=token;localStorage.setItem(TOKEN_KEY,githubToken);$('tokenInput').value='';updateGitHubStatus();toast('接続情報を登録しました')}
function disconnectGitHub(){githubToken='';localStorage.removeItem(TOKEN_KEY);$('tokenInput').value='';updateGitHubStatus();toast('GitHub書き込み認証を解除しました')}
async function getRemoteSave(id){let path=SAVE_DIR+'/'+encodeURIComponent(id)+'.json';try{let f=await ghJson(apiUrl('contents/'+path)+'?ref='+encodeURIComponent(SAVE_BRANCH));let obj=JSON.parse(fromBase64(f.content));obj._sha=f.sha;return obj}catch(e){if(e.status===404)return null;throw e}}
async function writeRemoteSave(save){if(!requireToken())throw Object.assign(new Error('GitHub接続が必要です'),{handled:true});let current=await getRemoteSave(save.id),path=SAVE_DIR+'/'+save.id+'.json',body={message:'Save '+save.name,content:toBase64(JSON.stringify({version:1,id:save.id,name:save.name,updatedAt:save.updatedAt,state:save.state},null,2)),branch:SAVE_BRANCH};if(current?._sha)body.sha=current._sha;let result=await ghJson(apiUrl('contents/'+path),{method:'PUT',body:JSON.stringify(body),headers:{'Content-Type':'application/json'}});return{...save,_sha:result.content?.sha||current?._sha}}
async function deleteRemoteSave(id,name){if(!requireToken())throw Object.assign(new Error('GitHub接続が必要です'),{handled:true});let path=SAVE_DIR+'/'+encodeURIComponent(id)+'.json';for(let attempt=0;attempt<2;attempt++){let current=await getRemoteSave(id);if(!current)return;try{await ghJson(apiUrl('contents/'+path),{method:'DELETE',body:JSON.stringify({message:'Delete save '+name,sha:current._sha,branch:SAVE_BRANCH}),headers:{'Content-Type':'application/json'}});return}catch(e){if((e.status===409||e.status===422)&&attempt===0)continue;throw e}}}
async function refreshSaves(){if(loadingSaves)return;loadingSaves=true;renderSaveList();try{let files=[];try{let list=await ghJson(apiUrl('contents/'+SAVE_DIR)+'?ref='+encodeURIComponent(SAVE_BRANCH));if(Array.isArray(list))files=list.filter(x=>x.type==='file'&&x.name.endsWith('.json'))}catch(e){if(e.status!==404)throw e}let vals=await Promise.all(files.map(async f=>{let data=await ghJson(f.url);let s=JSON.parse(fromBase64(data.content));s._sha=data.sha;return s}));store.slots={};for(let s of vals.filter(Boolean)){if(s?.id&&s?.state)store.slots[s.id]=s}renderSaveList()}catch(e){store.slots={};let msg=friendlyError(e);renderSaveList(msg);updateGitHubStatus(msg,true)}finally{loadingSaves=false;renderSaveList()}}
async function saveCurrent(){if(!activeId)return newCharacter();if(!requireToken())return;let btn=$('saveBtn');btn.disabled=true;let save={id:activeId,name:state.characterName||'旅人',updatedAt:Date.now(),state:clone(state)};try{let remote=await writeRemoteSave(save);store.slots[activeId]=remote;dirty=false;updateSaveState();renderSaveList();updateGitHubStatus('GitHub書き込み成功');toast('GitHubにセーブしました')}catch(e){if(!e.handled){let msg=friendlyError(e);openSave(false);updateGitHubStatus('SAVE失敗：'+msg,true);toast('SAVE失敗')}}finally{btn.disabled=false}}
async function newCharacter(){if(!requireToken())return;let name=prompt('新しいキャラクター名','旅人');if(name===null)return;name=name.trim()||'旅人';if(dirty&&!confirm('保存していない変更があります。保存せずに新しいキャラへ切り替えますか？'))return;let id=uid();activeId=id;state=fresh(name);dirty=true;closeStorage();closeSave();render();updateSaveState();await saveCurrent()}
function loadSlot(id){let slot=store.slots[id];if(!slot)return;if(dirty&&!confirm('保存していない変更があります。GitHubの保存時点をロードしますか？'))return;activeId=id;state=clone(slot.state);state.characterName=slot.name||state.characterName||'旅人';dirty=false;closeStorage();closeSave();render();updateSaveState();toast('ロードしました')}
async function renameSlot(id){if(!requireToken())return;let slot=store.slots[id];if(!slot)return;let name=prompt('キャラクター名を変更',slot.name);if(name===null)return;name=name.trim();if(!name)return;try{let save;if(id===activeId){if(dirty&&!confirm('このキャラには未保存の変更があります。名前変更と一緒にGitHubへ保存しますか？'))return;state.characterName=name;save={id,name,updatedAt:Date.now(),state:clone(state)}}else{let st=clone(slot.state);st.characterName=name;save={id,name,updatedAt:Date.now(),state:st}}let remote=await writeRemoteSave(save);store.slots[id]=remote;if(id===activeId){state=clone(remote.state);dirty=false}render();renderSaveList();updateSaveState();updateGitHubStatus('GitHub書き込み成功');toast('名前を変更してGitHubへ保存しました')}catch(e){if(!e.handled){let msg=friendlyError(e);openSave(false);updateGitHubStatus('名前変更失敗：'+msg,true);toast('名前変更失敗')}}}
async function deleteSlot(id){if(!requireToken())return;let slot=store.slots[id];if(!slot)return;let extra=(id===activeId&&dirty)?'\n未保存の変更も一緒に破棄されます。':'';if(!confirm('「'+slot.name+'」のGitHubセーブデータを削除しますか？'+extra))return;let btn=document.querySelector('[data-delete="'+id+'"]');if(btn){btn.disabled=true;btn.textContent='削除中…'}try{await deleteRemoteSave(id,slot.name);if(id===activeId){activeId=null;state=fresh('未選択');dirty=false;closeStorage()}delete store.slots[id];render();renderSaveList();updateSaveState();await refreshSaves();if(store.slots[id])throw new Error('GitHub上で削除を確認できませんでした');updateGitHubStatus('GitHubから削除しました');toast('削除しました')}catch(e){let msg=friendlyError(e);updateGitHubStatus('削除失敗：'+msg,true);toast('削除失敗')}finally{let b=document.querySelector('[data-delete="'+id+'"]');if(b){b.disabled=false;b.textContent='削除'}}}
function formatDate(t){if(!t)return'—';return new Date(t).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function renderSaveList(error=''){let l=$('saveList');l.innerHTML='';if(loadingSaves){l.innerHTML='<div class="note">GitHubから読み込み中…</div>';return}if(error){l.innerHTML='<div class="note">'+esc(error)+'</div>';return}let entries=Object.values(store.slots).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));if(!entries.length){l.innerHTML='<div class="note">GitHubのセーブデータはまだありません。</div>';return}for(let s of entries){let e=document.createElement('div');e.className='save-slot'+(s.id===activeId?' active':'');let actions=saveMode==='load'?'<button data-load="'+s.id+'">LOAD</button>':'<button data-rename="'+s.id+'">名前変更</button><button class="danger" data-delete="'+s.id+'">削除</button>';e.innerHTML='<div class="save-slot-top"><div><div class="save-slot-name">'+esc(s.name||'旅人')+'</div><div class="save-slot-date">GitHub保存 '+formatDate(s.updatedAt)+(s.id===activeId&&dirty?' ・ 現在は未保存変更あり':'')+'</div></div>'+(s.id===activeId?'<strong>使用中</strong>':'')+'</div><div class="save-slot-actions">'+actions+'</div>';l.appendChild(e)}if(saveMode==='load'){l.querySelectorAll('[data-load]').forEach(x=>x.onclick=()=>loadSlot(x.dataset.load))}else{l.querySelectorAll('[data-rename]').forEach(x=>x.onclick=()=>renameSlot(x.dataset.rename));l.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>deleteSlot(x.dataset.delete))}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setSaveMode(mode){saveMode=mode;let loadOnly=mode==='load';let title=document.querySelector('.save-head h2');if(title)title.textContent=loadOnly?'LOAD':'GitHubセーブデータ';let intro=document.querySelector('.save-box>.note');if(intro)intro.textContent=loadOnly?'GitHubに保存されたセーブデータを選んでロードします。':'キャラクターごとにGitHubの main ブランチの saves/characters へJSONファイルとして保存します。';let auth=document.querySelector('.github-box');if(auth)auth.style.display=loadOnly?'none':'';$('newSave').style.display=loadOnly?'none':'';let toolbar=document.querySelector('.save-toolbar');if(toolbar)toolbar.style.display=loadOnly?'none':''}
function openSave(refresh=true,mode='data'){setSaveMode(mode);$('saveLayer').classList.add('open');updateGitHubStatus();renderSaveList();if(refresh)refreshSaves()}
function openLoad(){openSave(true,'load')}
function closeSave(){$('saveLayer').classList.remove('open')}
